openapi: "3.0.3"
info:
  title: "Barcode Check API"
  description: "Check it the provided barcode is already used."
  version: "1.0.0"
servers:
  - url: "http://localhost:8080"
paths:
  /isused:
    get:
      summary: "GET isused"
      operationId: "isUsed"
      parameters:
        - name: "barcode"
          in: "query"
          required: true
          schema:
            type: "string"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  used:
                    type: boolean
                    description: "Indicates whether the barcode is used or not."
        '400':
          description: Bad request, value is missing or invalid.

